### PR TITLE
Changed proto to protocol

### PR DESCRIPTION
**Pull request by kmf**
Signed-off-by: Karl Fischer kmf@kmf.co

Fixes a depreciation

### CODE REVIEW

**Comment by kmf** [comment]
@burtlo can we merge this?

**Comment by burtlo** [comment]
I don't have write access to this repo anymore. I see that both of these InSpec extensions are not being supported. I'll reach out to good old Chef Training and the InSpec team to see if I can take them back under my control.

**Comment by kmf** [comment]
@burtlo you are the best!!!

**Comment by burtlo** [comment]
@kmf the request has been made. Since developing this plugin I've learned a little bit more about VSCode as far as adding tasks and tooling. When the write bit / ownership comes back my way I would love more of your support in making this an even better plugin. Are you in the Chef Community slack? If so reach out to me @burtlo.

**Comment by kmf** [comment]
Yes. I'm `kmf` pretty much everywhere

**Comment by SteveDelFante** [comment]
Hi Franklin. I gave you Write access to that repo. 

Cheers,
Steve


Steve Del Fante — Sr. Curriculum Developer 
425-231-9916 – sdelfante@chef.io 

Chef Software
chef.io

**Comment by burtlo** [comment]
Merged. I'll add the missing resources and cut a release by tomorrow.

**Pull request merged**
